name: Run checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  cache-version: v1
  asdf-version: v0.10.2

jobs:
  setup-tools:
    name: ⬢ Setup tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3.1.0

      - name: Setup tools
        uses: ./.github/actions/setup-tools

  check-deps:
    name: 🧶 Check npm dependencies
    runs-on: ubuntu-latest
    needs: setup-tools

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3.1.0

      - name: Setup tools
        id: setup-tools
        uses: ./.github/actions/setup-tools

      - name: Install project dependencies
        run: npm i

      - name: Check for dependency duplicates in `package-lock.json`
        run: npm dedupe
        # continue-on-error: true

      # - name: Check for known security issues with the installed packages
      #   run: npm audit -AR --environment production --severity info

  run-lint:
    name: 🛠 Run lint
    runs-on: ubuntu-latest
    needs: setup-tools

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3.1.0

      - name: Setup tools
        id: setup-tools
        uses: ./.github/actions/setup-tools

      - name: Install project dependencies
        run: npm i

      - name: Format code
        run: npm run format:check
